server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # SPA Routing: Fallback to index.html for unknown routes
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Enhance caching for static assets
    location ~* \.(?:css|js|jpg|jpeg|gif|png|ico|json|svg|woff|woff2|ttf)$ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }
}
